import type { Metadata } from "next";
import { Outfit } from "next/font/google"; // Assuming you use a font like Outfit or Inter
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider"; // <--- Import this
import Navbar from "./components/Navbar"; // Your Navbar

const font = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning> 
      {/* ^ suppressHydrationWarning is required for next-themes to work without errors */}
      
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}